// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Item in *About → Quem Somos*
 */
export interface AboutDocumentDataQuemSomosItem {
  /**
   * Image field in *About → Quem Somos*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about.quem_somos[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Description field in *About → Quem Somos*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.quem_somos[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Item in *About → Missão Valores Visão*
 */
export interface AboutDocumentDataMissaoValoresVisaoItem {
  /**
   * Title field in *About → Missão Valores Visão*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.missao_valores_visao[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *About → Missão Valores Visão*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.missao_valores_visao[].description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;
}

/**
 * Item in *About → O que fazemos*
 */
export interface AboutDocumentDataOQueFazemosItem {
  /**
   * Image field in *About → O que fazemos*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about.o_que_fazemos[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Title field in *About → O que fazemos*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.o_que_fazemos[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *About → O que fazemos*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.o_que_fazemos[].description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;
}

/**
 * Content for About documents
 */
interface AboutDocumentData {
  /**
   * Quem Somos field in *About*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: about.quem_somos[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  quem_somos: prismic.GroupField<Simplify<AboutDocumentDataQuemSomosItem>>;

  /**
   * Missão Valores Visão field in *About*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: about.missao_valores_visao[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  missao_valores_visao: prismic.GroupField<
    Simplify<AboutDocumentDataMissaoValoresVisaoItem>
  >;

  /**
   * Porquê estudar na CDM field in *About*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.porque_estudar_na_cdm
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  porque_estudar_na_cdm: prismic.RichTextField;

  /**
   * Nossa História field in *About*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.nossa_historia
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  nossa_historia: prismic.RichTextField;

  /**
   * O que fazemos field in *About*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: about.o_que_fazemos[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  o_que_fazemos: prismic.GroupField<Simplify<AboutDocumentDataOQueFazemosItem>>;
}

/**
 * About document from Prismic
 *
 * - **API ID**: `about`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AboutDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<AboutDocumentData>, "about", Lang>;

/**
 * Item in *Contactos → Secção*
 */
export interface ContactDocumentDataSectionItem {
  /**
   * Nome da secção field in *Contactos → Secção*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.section[].sectionName
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  sectionName: prismic.KeyTextField;

  /**
   * Item 1 field in *Contactos → Secção*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.section[].item_1
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  item_1: prismic.KeyTextField;

  /**
   * Item 2 field in *Contactos → Secção*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.section[].item_2
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  item_2: prismic.KeyTextField;

  /**
   * Item 4 field in *Contactos → Secção*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.section[].item_4
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  item_4: prismic.KeyTextField;
}

/**
 * Content for Contactos documents
 */
interface ContactDocumentData {
  /**
   * Secção field in *Contactos*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.section[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  section: prismic.GroupField<Simplify<ContactDocumentDataSectionItem>>;
}

/**
 * Contactos document from Prismic
 *
 * - **API ID**: `contact`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ContactDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ContactDocumentData>,
    "contact",
    Lang
  >;

/**
 * Item in *Curso de música → Instrutores*
 */
export interface CursoDeMusicaDocumentDataInstrutoresItem {
  /**
   * Avatar field in *Curso de música → Instrutores*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: curso_de_musica.instrutores[].avatar
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  avatar: prismic.ImageField<never>;

  /**
   * Nome field in *Curso de música → Instrutores*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: curso_de_musica.instrutores[].nome
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  nome: prismic.KeyTextField;

  /**
   * Descrição field in *Curso de música → Instrutores*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: curso_de_musica.instrutores[].descricao
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  descricao: prismic.KeyTextField;
}

/**
 * Content for Curso de música documents
 */
interface CursoDeMusicaDocumentData {
  /**
   * Cover field in *Curso de música*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: curso_de_musica.cover
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  cover: prismic.ImageField<never>;

  /**
   * Nome field in *Curso de música*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: curso_de_musica.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Descrição field in *Curso de música*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: curso_de_musica.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Instrutores field in *Curso de música*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: curso_de_musica.instrutores[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  instrutores: prismic.GroupField<
    Simplify<CursoDeMusicaDocumentDataInstrutoresItem>
  >;

  /**
   * Duração field in *Curso de música*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: curso_de_musica.duracao
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  duracao: prismic.KeyTextField;

  /**
   * Investimento field in *Curso de música*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: curso_de_musica.investimento
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  investimento: prismic.NumberField;

  /**
   * Valor da inscrição field in *Curso de música*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: curso_de_musica.valor_da_inscricao
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  valor_da_inscricao: prismic.NumberField;
}

/**
 * Curso de música document from Prismic
 *
 * - **API ID**: `curso_de_musica`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CursoDeMusicaDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<CursoDeMusicaDocumentData>,
    "curso_de_musica",
    Lang
  >;

/**
 * Item in *Membros → Membro*
 */
export interface MembrosDocumentDataMembroItem {
  /**
   * Avatar field in *Membros → Membro*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: membros.membro[].avatar
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  avatar: prismic.ImageField<never>;

  /**
   * Name field in *Membros → Membro*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: membros.membro[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Cargo field in *Membros → Membro*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: membros.membro[].cargo
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cargo: prismic.KeyTextField;

  /**
   * Descrição field in *Membros → Membro*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: membros.membro[].descricao
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  descricao: prismic.KeyTextField;

  /**
   * Categoria field in *Membros → Membro*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: membros.membro[].category
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  category: prismic.SelectField<"Membros" | "Direcção">;
}

/**
 * Content for Membros documents
 */
interface MembrosDocumentData {
  /**
   * Membro field in *Membros*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: membros.membro[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  membro: prismic.GroupField<Simplify<MembrosDocumentDataMembroItem>>;
}

/**
 * Membros document from Prismic
 *
 * - **API ID**: `membros`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MembrosDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<MembrosDocumentData>,
    "membros",
    Lang
  >;

/**
 * Content for Notícia documents
 */
interface NewsDocumentData {
  /**
   * Capa field in *Notícia*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: news.cover
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  cover: prismic.ImageField<never>;

  /**
   * Titulo field in *Notícia*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: news.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Categoria field in *Notícia*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: news.categoria
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  categoria: prismic.KeyTextField;

  /**
   * Author field in *Notícia*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: news.author
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  author: prismic.KeyTextField;

  /**
   * Conteúdo field in *Notícia*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: news.content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;
}

/**
 * Notícia document from Prismic
 *
 * - **API ID**: `news`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NewsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<NewsDocumentData>, "news", Lang>;

/**
 * Item in *Nossas Estatísticas → Números*
 */
export interface OurNumbersDocumentDataNumbersItem {
  /**
   * Nome field in *Nossas Estatísticas → Números*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ourNumbers.numbers[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Valor field in *Nossas Estatísticas → Números*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ourNumbers.numbers[].value
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  value: prismic.KeyTextField;
}

/**
 * Content for Nossas Estatísticas documents
 */
interface OurNumbersDocumentData {
  /**
   * Números field in *Nossas Estatísticas*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: ourNumbers.numbers[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  numbers: prismic.GroupField<Simplify<OurNumbersDocumentDataNumbersItem>>;
}

/**
 * Nossas Estatísticas document from Prismic
 *
 * - **API ID**: `ourNumbers`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type OurNumbersDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<OurNumbersDocumentData>,
    "ourNumbers",
    Lang
  >;

/**
 * Item in *Parceiros → Parceiros*
 */
export interface ParceirosDocumentDataParceirosItem {
  /**
   * Logo field in *Parceiros → Parceiros*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: parceiros.parceiros[].logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * Nome field in *Parceiros → Parceiros*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: parceiros.parceiros[].nome
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  nome: prismic.KeyTextField;

  /**
   * Description field in *Parceiros → Parceiros*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: parceiros.parceiros[].description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;
}

/**
 * Content for Parceiros documents
 */
interface ParceirosDocumentData {
  /**
   * Parceiros field in *Parceiros*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: parceiros.parceiros[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  parceiros: prismic.GroupField<Simplify<ParceirosDocumentDataParceirosItem>>;
}

/**
 * Parceiros document from Prismic
 *
 * - **API ID**: `parceiros`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ParceirosDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ParceirosDocumentData>,
    "parceiros",
    Lang
  >;

/**
 * Content for Serviços documents
 */
interface ServicesDocumentData {
  /**
   * Nome field in *Serviços*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Imagem field in *Serviços*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: services.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Descrição field in *Serviços*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Imagem de capa field in *Serviços*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: services.cover_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  cover_image: prismic.ImageField<never>;
}

/**
 * Serviços document from Prismic
 *
 * - **API ID**: `services`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ServicesDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ServicesDocumentData>,
    "services",
    Lang
  >;

/**
 * Item in *Professores → professor*
 */
export interface TeachersDocumentDataProfessorItem {
  /**
   * Avatar field in *Professores → professor*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: teachers.professor[].avatar
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  avatar: prismic.ImageField<never>;

  /**
   * Nome field in *Professores → professor*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: teachers.professor[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Cargo field in *Professores → professor*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: teachers.professor[].role
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  role: prismic.KeyTextField;

  /**
   * Descrição field in *Professores → professor*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: teachers.professor[].description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;
}

/**
 * Content for Professores documents
 */
interface TeachersDocumentData {
  /**
   * professor field in *Professores*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: teachers.professor[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  professor: prismic.GroupField<Simplify<TeachersDocumentDataProfessorItem>>;
}

/**
 * Professores document from Prismic
 *
 * - **API ID**: `teachers`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TeachersDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<TeachersDocumentData>,
    "teachers",
    Lang
  >;

/**
 * Item in *Testemunhos → testemonial*
 */
export interface TestemonialsDocumentDataTestemonialItem {
  /**
   * Avatar field in *Testemunhos → testemonial*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: testemonials.testemonial[].avatar
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  avatar: prismic.ImageField<never>;

  /**
   * Name field in *Testemunhos → testemonial*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testemonials.testemonial[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Cargo field in *Testemunhos → testemonial*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testemonials.testemonial[].role
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  role: prismic.KeyTextField;

  /**
   * Descrição field in *Testemunhos → testemonial*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testemonials.testemonial[].description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;
}

/**
 * Content for Testemunhos documents
 */
interface TestemonialsDocumentData {
  /**
   * testemonial field in *Testemunhos*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: testemonials.testemonial[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  testemonial: prismic.GroupField<
    Simplify<TestemonialsDocumentDataTestemonialItem>
  >;
}

/**
 * Testemunhos document from Prismic
 *
 * - **API ID**: `testemonials`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TestemonialsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<TestemonialsDocumentData>,
    "testemonials",
    Lang
  >;

/**
 * Item in *Porquê nos Escolher → Motivos*
 */
export interface WhychooseusDocumentDataWhysItem {
  /**
   * Titulo field in *Porquê nos Escolher → Motivos*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: whychooseus.whys[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Descrição field in *Porquê nos Escolher → Motivos*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: whychooseus.whys[].description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;
}

/**
 * Content for Porquê nos Escolher documents
 */
interface WhychooseusDocumentData {
  /**
   * Motivos field in *Porquê nos Escolher*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: whychooseus.whys[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  whys: prismic.GroupField<Simplify<WhychooseusDocumentDataWhysItem>>;
}

/**
 * Porquê nos Escolher document from Prismic
 *
 * - **API ID**: `whychooseus`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type WhychooseusDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<WhychooseusDocumentData>,
    "whychooseus",
    Lang
  >;

export type AllDocumentTypes =
  | AboutDocument
  | ContactDocument
  | CursoDeMusicaDocument
  | MembrosDocument
  | NewsDocument
  | OurNumbersDocument
  | ParceirosDocument
  | ServicesDocument
  | TeachersDocument
  | TestemonialsDocument
  | WhychooseusDocument;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      AboutDocument,
      AboutDocumentData,
      AboutDocumentDataQuemSomosItem,
      AboutDocumentDataMissaoValoresVisaoItem,
      AboutDocumentDataOQueFazemosItem,
      ContactDocument,
      ContactDocumentData,
      ContactDocumentDataSectionItem,
      CursoDeMusicaDocument,
      CursoDeMusicaDocumentData,
      CursoDeMusicaDocumentDataInstrutoresItem,
      MembrosDocument,
      MembrosDocumentData,
      MembrosDocumentDataMembroItem,
      NewsDocument,
      NewsDocumentData,
      OurNumbersDocument,
      OurNumbersDocumentData,
      OurNumbersDocumentDataNumbersItem,
      ParceirosDocument,
      ParceirosDocumentData,
      ParceirosDocumentDataParceirosItem,
      ServicesDocument,
      ServicesDocumentData,
      TeachersDocument,
      TeachersDocumentData,
      TeachersDocumentDataProfessorItem,
      TestemonialsDocument,
      TestemonialsDocumentData,
      TestemonialsDocumentDataTestemonialItem,
      WhychooseusDocument,
      WhychooseusDocumentData,
      WhychooseusDocumentDataWhysItem,
      AllDocumentTypes,
    };
  }
}
